# Generated by Django 5.2.7 on 2025-10-08 13:59

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clothing_type',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('color_palette', models.JSONField(blank=True, null=True)),
                ('event_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'style',
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('feels_like', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('wind', models.FloatField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True, null=True)),
                ('precipitation_prob', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('cloudiness', models.IntegerField(blank=True, null=True)),
                ('uv_index', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'weather',
            },
        ),
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('last_used', models.DateField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('formality', models.TextField(blank=True, null=True)),
                ('main_color', models.TextField(blank=True, null=True)),
                ('secondary_colors', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='clothing_items', to='myapi.user')),
                ('type', models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapi.clothingtype')),
            ],
            options={
                'db_table': 'clothing_item',
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='myapi.user')),
                ('style', models.ForeignKey(db_column='style_id', on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='myapi.style')),
            ],
            options={
                'db_table': 'preference',
                'unique_together': {('style', 'user')},
            },
        ),
        migrations.CreateModel(
            name='StyleClothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing', models.ForeignKey(db_column='clothing_id', on_delete=django.db.models.deletion.CASCADE, related_name='clothing_styles', to='myapi.clothingitem')),
                ('style', models.ForeignKey(db_column='style_id', on_delete=django.db.models.deletion.CASCADE, related_name='style_clothing', to='myapi.style')),
            ],
            options={
                'db_table': 'style_clothing',
                'unique_together': {('style', 'clothing')},
            },
        ),
        migrations.CreateModel(
            name='WeatherClothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing', models.ForeignKey(db_column='clothing_id', on_delete=django.db.models.deletion.CASCADE, related_name='weather_links', to='myapi.clothingitem')),
                ('weather', models.ForeignKey(db_column='weather_id', on_delete=django.db.models.deletion.CASCADE, related_name='clothing_links', to='myapi.weather')),
            ],
            options={
                'db_table': 'weather_clothing',
                'unique_together': {('clothing', 'weather')},
            },
        ),
    ]
