# Generated by Django 5.2.7 on 2025-10-09 15:11

import django.db.models.deletion
import myapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_clothingtype_style_weather_clothingitem_preference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to=myapi.models.photo_upload_to)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/clothing/thumbnails/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'photo',
            },
        ),
        migrations.RemoveField(
            model_name='clothingitem',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='photo',
            field=models.ForeignKey(blank=True, db_column='photo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clothing_items', to='myapi.photo'),
        ),
    ]
