# Generated by Django 5.2.7 on 2025-10-14 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'outfit',
            },
        ),
        migrations.CreateModel(
            name='OutfitClothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing', models.ForeignKey(db_column='clothing_id', on_delete=django.db.models.deletion.CASCADE, related_name='outfit_links', to='myapi.clothingitem')),
                ('outfit', models.ForeignKey(db_column='outfit_id', on_delete=django.db.models.deletion.CASCADE, related_name='outfit_links', to='myapi.outfit')),
            ],
            options={
                'db_table': 'outfit_clothing',
                'unique_together': {('outfit', 'clothing')},
            },
        ),
        migrations.AddField(
            model_name='outfit',
            name='clothing_items',
            field=models.ManyToManyField(related_name='outfits', through='myapi.OutfitClothing', through_fields=('outfit', 'clothing'), to='myapi.clothingitem'),
        ),
    ]
