services:
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_DB: oufitlab
      POSTGRES_USER: oufitlabuser
      POSTGRES_PASSWORD: oufitlabpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oufitlabuser -d oufitlab"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
    env_file:
      - ./backend/.env


  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    env_file:
      - ./frontend/.env

volumes:
  postgres_data:
  frontend_node_modules:
